#!/usr/bin/env python
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
import telegram
import requests

path = '/home/Python/TradingBot/READ/WalletAddress'
pathnew = '/home/Python/TradingBot/READ/WalletValueOld'
with open(path) as fp:
 lines = fp.read().splitlines()
 count = 0
 ff = open(pathnew, "w")
 for line in lines:
  try:
   wallet = lines[count]
   url = 'https://blockchain.info/balance?active='+wallet
   try:
    session = Session()
    response = session.get(url)
    datajson = json.loads(response.text)
    finalbalance = datajson[wallet]['final_balance']
    print(wallet)
    ff.write(str(finalbalance)+'\n')
    count += 1
   except (ConnectionError, Timeout, TooManyRedirects) as e:
    print(e)
  except (ValueError, Timeout, TooManyRedirects) as e:
   print(e)
