#!/usr/bin/env python
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

path = 'PATH/WalletAddress'
pathvalue = 'PATH/WalletValue'
with open(path) as fp:
 lines = fp.read().splitlines()
 count = 0
 ff = open(pathvalue, "w")
 for line in lines:
  wallet = lines[count]
  url = 'https://blockchain.info/balance?active='+wallet
  try:
   session = Session()
   response = session.get(url)
   datajson = json.loads(response.text)
   wbalance = response.json()
   finalbalance = datajson[wallet]['final_balance']/100000000000
   print(wallet, finalbalance)
   ff.write(str(datajson[wallet]['final_balance'])+ '\n')
   count += 1
  except (ConnectionError, Timeout, TooManyRedirects) as e:
   count +=1
   print(e)
