#!/usr/bin/env python
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

path = '/home/Python/TradingBot/READ/MinersRevenue'
pathrat = '/home/Python/TradingBot/READ/RATIO/MinersRevenue'
f = open(path, "r")
x = open(pathrat, "w")
url = 'https://api.blockchain.info/charts/miners-revenue?timespan=1days&sampled=true&metadata=false&cors=true&format=json'
parameters = {

}
headers = {
  'Accepts': 'application/json',

}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  datajson = json.loads(response.text)
  hashrate = response.json()
  length = (len(datajson['values']))
  miners = datajson['values'][length-1]['y']
  miners2 = datajson['values'][length-2]['y']
  minersrat = float(miners)/float(miners2)

  print(str(miners/1000000))
  with open(path, 'w') as f:
   f.write(str(miners/1000000))
   x.write(str(minersrat))

except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)
