#!/usr/bin/env python
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
import requests

path = '/home/Python/TradingBot/READ/MVRV'
pathrat = '/home/Python/TradingBot/READ/RATIO/MVRV'
f = open(path, "r")
x = open(pathrat, "w")
url = 'https://www.lookintobitcoin.com/django_plotly_dash/app/mvrv_zscore/_dash-update-component'
parameters = {

}
headers = {
  'Accepts': 'application/json',
        'User-Agent':   'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0'

}
request_data = {
 'output': 'chart.figure',
 'changedPropIds': [
   'url.pathname'
 ],
 'inputs': [
     {
        'id': 'url',
        'property': 'pathname',
        'value': '/charts/mvrv-zscore/'
     }
   ]
}

session = Session()
try:
  response = requests.post(url, json=request_data)
  response_json = response.json()

  length = len(response_json['response']['props']['figure']['data'][0]['y'])
  mvrv = response_json['response']['props']['figure']['data'][0]['y'][length-1]
  mvrv2 = mvrv = response_json['response']['props']['figure']['data'][0]['y'][length-2]
  mvrvrat = float(mvrv)/float(mvrv2)

  print(str(mvrv))#,str(hashrate))#,str(oldvalue[0]),str(change))
  with open(path, 'w') as f:
   f.write(str(mvrv))
   x.write(str(mvrvrat))
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)
